language: cpp
dist: trusty
# sudo: required
addons:
  apt:
    packages:
      - gfortran
      - zlib1g-dev
      - libhdf5-dev 
os:
  - linux
# - osx
#osx_image: xcode9
branches:
  only:
  - master
  - travis
before_install: ".travis/install.sh"
script: ".travis/build.sh"
