language: cpp

# Run jobs on a container based infrastructure, overridden by job
sudo: false

branches:
  only:
  - master
  - travis
  
matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          packages:
            - gfortran
            - zlib1g-dev
            - libhdf5-dev 
    - os: osx
      osx_image: xcode9
      sudo: required
      
# before_install: ".travis/install.sh"
before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]
    then 
      curl -L -o gfortran-7.1-bin.tgz -fs "https://downloads.sourceforge.net/project/hpc/hpc/g95/gfortran-7.1-bin.tar.gz?r=&ts=1508458128&use_mirror=svwh"
      gunzip gfortran-7.1-bin.tgz
      sudo tar -xf gfortran-7.1-bin.tar -C /
      HOMEBREW_NO_AUTO_UPDATE=1 brew install cmake
      HOMEBREW_NO_AUTO_UPDATE=1 brew install boost
      HOMEBREW_NO_AUTO_UPDATE=1 brew install hdf5@1.8 --c++11
    fi
    
install:
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]
    then 
      curl -fsO "https://downloads.sourceforge.net/project/hpc/hpc/g95/gfortran-7.1-bin.tar.gz?r=&ts=1508458128&use_mirror=svwh"
      gunzip gfortran-7.1-bin.tar.gz
      sudo tar -xvf gfortran-7.1-bin.tar -C / 
      brew install cmake
      brew install boost
      brew tap homebrew/science
      brew install homebrew/science/hdf5@1.8 --c++11
    fi
script: ".travis/build.sh"
