version: 1.1.0-{build}

image: Visual Studio 2015

environment:
  GENERATOR: MinGW Makefiles
  PACMAN: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\

configuration: Release
platform: x64

#init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Syu"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S msys/git"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S mingw64/mingw-w64-x86_64-gcc"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S mingw64/mingw-w64-x86_64-gcc-fortran"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S mingw64/mingw-w64-x86_64-cmake"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S mingw64/mingw-w64-x86_64-doxygen"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S msys/make"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S mingw-w64-x86_64-pkg-config"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S mingw-w64-x86_64-hdf5"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S mingw-w64-x86_64-libzip"
#  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S mingw-w64-x86_64-boost"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S mingw-w64-x86_64-netcdf"

build_script:
  - ps: .\.appveyor\build.ps1
  - cmd: dir
  - cmd: dir \projects\vcell-solvers\build
  - cmd: dir \projects\vcell-solvers\build\bin
  
after_build:
  - C:\msys64\usr\bin\bash -lc "cd bin && ls bin/*.exe | awk '{print $1}' | xargs -I '{}' ldd '{}' | grep "=> /" | grep -v "build" | awk '{print $3}' | xargs -I '{}' cp -vn '{}' . || true && cd .."
  - C:\msys64\usr\bin\bash -lc "cd bin && ls bin/*.dll | awk '{print $1}' | xargs -I '{}' ldd '{}' | grep "=> /" | grep -v "build" | awk '{print $3}' | xargs -I '{}' cp -vn '{}' . || true && cd .."
  - C:\msys64\usr\bin\bash -lc "cd bin && ls bin/*.dll | awk '{print $1}' | xargs -I '{}' ldd '{}' | grep "=> /" | grep -v "build" | awk '{print $3}' | xargs -I '{}' cp -vn '{}' . || true && cd .."
  - cmd: 7z a %APPVEYOR_BUILD_FOLDER%\build\win64.zip %APPVEYOR_BUILD_FOLDER%\build\bin\*
  
artifacts:
  - path: build\win64.zip
    name: win64_archive
    
deploy:
  release: solvers-v$(appveyor_build_version)
  description: 'appveyor build for windows 64'
  provider: GitHub
  auth_token:
    secure: 4uZuKhrabKUiZTYp37aP67amqnXcGjLvDEkp8G4lv4i76sL8TIm8hE/vPC5hUOUf
  artifact: win64_archive
  draft: false
  prerelease: false
  on:
    branch: master               # release from master branch only
    appveyor_repo_tag: false     # deploy always, not just on tag push
